services:
  twitch-raid-webhook:
    image: "ghcr.io/wissididom/twitch-raid-webhook"
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
    env_file: .env
